
name: CI Build

on: [push, pull_request]

jobs:
        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd ..
        cd ..
        cd DailyTaskTimeTracker
        cd DailyTaskTimeTracker
        cd DailyTaskTimeTracker
        cd DailyTaskTimeTracker.Android
        msbuild DailyTaskTimeTracker.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
